export const CURRENCIES_DATA = [
  { code: "UAH", name: "Українська гривня", rateToUAH: 1 },
  { code: "USD", name: "Долар США", rateToUAH: 38.50 },
  { code: "EUR", name: "Євро", rateToUAH: 41.20 },
  { code: "GBP", name: "Англійський фунт", rateToUAH: 48.00 },
  { code: "AUD", name: "Австралійський долар", rateToUAH: 25.00 },
  { code: "CAD", name: "Канадський долар", rateToUAH: 28.00 },
  { code: "CHF", name: "Швейцарський франк", rateToUAH: 43.00 },
  { code: "CNY", name: "Китайський юань", rateToUAH: 5.40 },
  { code: "JPY", name: "Японська єна", rateToUAH: 0.27 },
  { code: "SEK", name: "Шведська крона", rateToUAH: 3.40 },
  { code: "NOK", name: "Норвезька крона", rateToUAH: 3.20 },
  { code: "PLN", name: "Польський злотий", rateToUAH: 8.70 },
  { code: "ILS", name: "Ізраїльський шекель", rateToUAH: 10.50 },
  { code: "TRY", name: "Турецька ліра", rateToUAH: 1.06 },
];
